# Generated by Django 5.2.6 on 2025-09-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('ADS', 'Análise e Desenvolvimento de Sistemas'), ('DIR', 'Direito'), ('ADM', 'Administração'), ('PED', 'Pedagogia'), ('ENF', 'Enfermagem')], max_length=3),
        ),
    ]
